
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='secret_share',
    version='0.1.0',
    description='Simple private file and URL sharing',
    python_requires='==3.*,>=3.7.0',
    author='Przemysław Palacz',
    author_email='pprzemal@gmail.com',
    packages=['secret_share', 'secret_share.settings', 'secret_share.user_shares', 'secret_share.user_shares.migrations', 'secret_share.users', 'secret_share.users.middleware', 'secret_share.users.migrations'],
    package_data={},
    install_requires=['django==2.*,>=2.2.0'],
    extras_require={'dev': ['pytest==3.*,>=3.0.0']},
)
